import { expect, test } from "@playwright/test";
import  dotenv from "dotenv";
import path from "path";

const environment = process.env.NODE_ENV || 'testing'
const envPath = path.resolve(__dirname, `../../test-data/${environment}.env`)
dotenv.config({path:envPath})

test.setTimeout(40000)

test('title for the test case is ',async({page})=>{
    await page.goto("https://prelive-au-customer.worldoptions.com/#/Login")
    await page.getByPlaceholder("Enter username").fill("stewarttest")
    await page.getByPlaceholder("Enter password").fill("psc123$")
    await page.getByText("Continue").click()
    const spinner = page.locator("//div[@class='la-ball-beat la-2x']")
    await expect(spinner,'spinner loading completed').not.toBeVisible({timeout:10000})
    await page.waitForTimeout(2000)
    await page.getByPlaceholder("Company").nth(1).fill("Allied test company")
    await page.getByPlaceholder("Contact Name").nth(1).fill("Sathish R")
    await page.getByPlaceholder("Address 1").nth(1).fill("500 allied street")
    await page.getByPlaceholder("Select country").nth(1).click()
    await page.getByRole('option', { name: 'AUSTRALIA' }).locator('span').click()
    await page.getByPlaceholder("Select state").nth(1).click()
    await page.getByText("Queensland").click()
    await page.getByPlaceholder("City").nth(1).fill("BRISBANE CITY")
    await page.locator("[formcontrolname='PostalCode']").nth(1).fill("4000")
    await page.getByPlaceholder("Area").nth(1).fill("044")
    await page.getByPlaceholder("Phone number").nth(1).fill("866769")
    await page.getByPlaceholder("Email address").nth(1).fill("sathish@gmail.com")
    await page.getByPlaceholder("Select one").nth(0).click()
    await page.getByText("TNT",{exact:true}).click()
    await page.getByPlaceholder("Select one").nth(1).click()
    await page.getByText("Domestic Road Express").click()
    await page.getByPlaceholder("Select one").nth(2).click()
    await page.getByText("Non-Document (Carton)").click()
    await page.getByPlaceholder("Enter Customer Reference ").fill("2008")
    await page.locator(".mat-radio-label-content").filter({hasText:"No"}).click()
    await page.getByPlaceholder("ATL Description").fill("I need ATL")
    await page.getByPlaceholder("Unit").fill("15")
    await page.getByPlaceholder("L",{exact:true}).fill("30")
    await page.getByPlaceholder("W",{exact:true}).fill("30")
    await page.getByPlaceholder("H",{exact:true}).fill("30")
    await page.getByRole('button', { name: 'Quote' }).click()
    await page.getByRole('button', { name: 'Ok' }).click()
    await page.getByRole("button",{name :'Next'}).click()
    const collection = page.locator("//p[text()='Drop at a Depot']/preceding::div[6]")
    await collection.click()
})
